In [1]:
2+3+9

14

In [2]:
99 - 73

26

In [3]:
23.54 * -1432

-33709.28

In [4]:
100 / 7

14.285714285714286

In [5]:
100 // 7

14

In [6]:
100%7

2

In [7]:
5 ** 3

125

In [8]:
!pip install numpy
!pip install pandas


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
!pip install matplotlib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
!pip install -U scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [11]:
!pip install preprocessing

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 349 kB 24.8 MB/s 
     |████████████████████████████████| 1.4 MB 36.5 MB/s 
     |████████████████████████████████| 1.2 MB 48.7 MB/s 
  Created wheel for nltk: filename=nltk-3.2.4-py3-none-any.whl size=1367721 sha256=9acf66bc3e647e8af71088cb2819088a3d577d3f02edf507fcecba32779a23ed
  Stored in directory: /root/.cache/pip/wheels/90/5e/9e/4cb46185f2a16c60e6fc524372ba7fef89ce3347734c8798b6
Successfully built nltk
  Attempting uninstall: nltk
    Found existing installation: nltk 3.7
    Uninstalling nltk-3.7:
      Successfully uninstalled nltk-3.7


**Sample Data**

In [12]:
import numpy as np
from sklearn import preprocessing

In [14]:
sample_data = np.array ([[2.1, -1.9, 5.5],
                         [-1.5, 2.4, 3.5],
                         [0.5, -7.9, 5.6],
                         [5.9, 2.3, -5.8]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [15]:
sample_data.shape

(4, 3)

Teknik Binarisation


In [18]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [17]:
#parameter yang digunakan untuk ambang batas
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data  

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Teknik Scalling

In [20]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [24]:
#Scalling Min Max Scaller
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)

#Cara 1
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [25]:
#Cara 2
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Teknik Normalization L1

```
# This is formatted as code
```



In [26]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [27]:
l1_normalization_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalization_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

Teknik Normalization L2

In [28]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [29]:
l1_normalization_data = preprocessing.normalize(sample_data, norm='l2')
l1_normalization_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

Encoding

In [34]:
label_kategori = ['senin','selasa','rabu','kamis','jumat','sabtu','minggu']
encoder = preprocessing.LabelEncoder()
encoder.fit(label_kategori)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '=', i)


Label mapping:
jumat = 0
kamis = 1
minggu = 2
rabu = 3
sabtu = 4
selasa = 5
senin = 6


**Training set dan Test Set**

In [40]:
from sklearn.model_selection import train_test_split

x_data = range(10)
y_data = range(10)

print("random_state ditentukan")
for i in range(3):
  x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=42)
  print(y_test)

random_state ditentukan
[8, 1, 5]
[8, 1, 5]
[8, 1, 5]


In [41]:

print("random_state tidak ditentukan")
for i in range(3):
  x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=None)
  print(y_test)

random_state tidak ditentukan
[4, 2, 9]
[9, 7, 5]
[2, 7, 9]
